### ISSUE TITLE
ImportError: MD5 Hashes of supplied model_files do not match the known_hashes argument.

### ISSUE THREAD

**Issue by balandongiv** [Tobias-Fischer/rt_gene#97] opened 2021-03-13 13:52 UTC
When executing the `estimate_gaze_standalone` with `pytorch`  as the beckend.

I got the error `ImportError` 

> MD5 Hashes of supplied model_files do not match the known_hashes argument. If you are training your "
>                 "own models, then please supply the md5sum hashes in the known_hashes argument. If you're not, "
>                 "then you're using old models. The newer models should have downloaded already so please update the "
>                 "estimate_gaze.launch file that you've modified.

However, the code run without any run time error  with `tensorflow`  as the beckend.

I am using the [master](https://github.com/Tobias-Fischer/rt_gene/tree/master/rt_gene_standalone) version.

**Comment by Tobias-Fischer** [comment] 2021-03-14 20:58
Hi @balandongiv,
Could you please check the md5 sum of the models that you have downloaded? They live in `./rt_gene/rt_gene/model_nets/`. Could you please report
```
md5sum gaze_model_pytorch_vgg16_prl_mpii_allsubjects1.model
md5sum gaze_model_pytorch_vgg16_prl_mpii_allsubjects2.model
md5sum gaze_model_pytorch_vgg16_prl_mpii_allsubjects3.model
md5sum gaze_model_pytorch_vgg16_prl_mpii_allsubjects4.model
```

The result should be sth like
```
(robostackenv) tobias@QUTLAB:~$ md5sum gaze_model_pytorch_vgg16_prl_mpii_allsubjects1.model
ae435739673411940eed18c98c29bfb1  gaze_model_pytorch_vgg16_prl_mpii_allsubjects1.model
(robostackenv) tobias@QUTLAB:~$ md5sum gaze_model_pytorch_vgg16_prl_mpii_allsubjects2.model
4afd7ccf5619552ed4a9f14606b7f4dd  gaze_model_pytorch_vgg16_prl_mpii_allsubjects2.model
(robostackenv) tobias@QUTLAB:~$ md5sum gaze_model_pytorch_vgg16_prl_mpii_allsubjects3.model
743902e643322c40bd78ca36aacc5b4d  gaze_model_pytorch_vgg16_prl_mpii_allsubjects3.model
(robostackenv) tobias@QUTLAB:~$ md5sum gaze_model_pytorch_vgg16_prl_mpii_allsubjects4.model
```

**Comment by balandongiv** [comment] 2021-03-16 03:42
Hi @Tobias-Fischer,the  `md5sum` for the gaze_model_pytorch_vgg16_prl_mpii_allsubjects for id 1,2,3 are the same as post by you. Can you kindly cross check whether  `md5sum gaze_model_pytorch_vgg16_prl_mpii_allsubjects4.model` of mine is similar as yours since you did not share it in your initial post.
```
ae435739673411940eed18c98c29bfb1    gaze_model_pytorch_vgg16_prl_mpii_allsubjects1.model
4afd7ccf5619552ed4a9f14606b7f4dd    gaze_model_pytorch_vgg16_prl_mpii_allsubjects2.model
743902e643322c40bd78ca36aacc5b4d    gaze_model_pytorch_vgg16_prl_mpii_allsubjects3.model
06a10f43088651053a65f9b0cd5ac4aa    gaze_model_pytorch_vgg16_prl_mpii_allsubjects4.model
```

**Comment by Tobias-Fischer** [comment] 2021-03-16 03:54
I have the same md5sums. Are you using a modified launch file? Or is everything taken from the repository without modifications?

**Comment by balandongiv** [comment] 2021-03-16 04:00
I am using the `master` version and nothing is modified.

May I know what do you mean by `modified launch file`?

**Comment by Tobias-Fischer** [comment] 2021-03-16 04:06
Thanks for helping me to debug this. In the `rt_gene/rt_gene/src/rt_gene/estimate_gaze_pytorch.py` file can you please add a `print(_model_hashes)` and `print(_correct)` after line 23, and let me know the output?

**Comment by balandongiv** [comment] 2021-03-16 04:12
Here are the outputs

```
_model_hashes: ['e55ea59d494d66dd075bf1503a32f99c']
_correct: [1]
```

I believe the var `_correct` is the culprit.

**Comment by Tobias-Fischer** [comment] 2021-03-16 04:19
I see what the mistake is. The single model in https://github.com/Tobias-Fischer/rt_gene/blob/0a93423fdd7c8d6dd0be1fbb5357d5a645125da8/rt_gene_standalone/estimate_gaze_standalone.py#L150 hasn't been updated.

@ahmed-alhindawi - could you please train a model on all subjects, upload it, and add the hash to the known hashes?

**Comment by Tobias-Fischer** [comment] 2021-03-16 04:22
The issue is that you don't change the `--models` argument to point to a PyTorch model. Simply issue `--models /path/to/gaze_model_pytorch_vgg16_prl_mpii_allsubjects1.model` and it will work.

**Comment by Tobias-Fischer** [comment] 2021-03-16 04:22
Closing here - feel free to reopen if it doesn't work.

**Closed by Tobias-Fischer** 2021-03-16 04:22 UTC

**Comment by balandongiv** [comment] 2021-03-16 04:30
Thanks, it solve the issue.

Just a suggestion. Is it possible to update or add extra information on the `warning`

`rt_gene/rt_gene/src/rt_gene/estimate_gaze_pytorch.py` line 27, to include about the requirement to change the `--models argument` if one to encounter error whenever the select either `tensorflow`  or `PyTorch` model

> 
> 
> The issue is that you don't change the `--models` argument to point to a PyTorch model. Simply issue `--models /path/to/gaze_model_pytorch_vgg16_prl_mpii_allsubjects1.model` and it will work.

**Comment by Tobias-Fischer** [comment] 2021-03-16 04:45
You are right - done.
